baseURL = "https://www.samuelkillermann.com/"
languageCode = "en-us"
title = "Created by Sam Killermann"
theme= "hugo-paper"

[params]
    author = "Sam Killermann"
    description = "Sam's internet house! Featuring Killermann's work -- books, TEDxTalks, edugraphics, comedy shows, gender & sexuality & social justice resources -- that has reached hundreds of millions of people in over 238 countries."
    og_image = "/img/sK-Social-Card-2018.png"

[build]
    publish = "public"
    command = "hugo"

[menu]

[[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = -130

[[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "https://www.samkillermann.com/"
    weight = -120

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -110

[[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = -100

[[menu.main]]
    identifier = "bio"
    name = "Bio"
    url = "/bio/"
    weight = -90

[[menu.main]]
    identifier = "links"
    url ="/links/"
    name = "Links"
    weight = -80

[taxonomies]
    skills = "skills"
    tags = "tags"

[context.production.environment]
    HUGO_VERSION = "0.52"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.52"
